export const mockCasinosData = [
    {
        id: 'duel',
        name: 'Duel',
        logo: 'https://files.catbox.moe/p4z3v7.jpg',
        bonus: '200% up to 1 BTC + 50 FS',
        description: 'Fast-paced gaming with tournaments and instant BTC withdrawals.',
        tags: ['all', 'high-bonus', 'new'],
        rating: 4.7,
        reviewCount: 189,
        withdrawalTime: '~7 mins',
        certified: true,
    },
    {
        id: 'stake',
        name: 'Stake',
        logo: 'https://files.catbox.moe/klt24q.jpg',
        bonus: '200% up to $1000',
        description: 'Provably fair games and massive sports options with 20+ cryptos.',
        tags: ['all', 'high-bonus', 'sports', 'live'],
        rating: 4.8,
        reviewCount: 2133,
        withdrawalTime: '~5 mins',
        certified: true,
    },
    {
        id: 'sportsbet-io',
        name: 'Sportsbet.io',
        logo: 'https://files.catbox.moe/v2jp51.jpg',
        bonus: '100% up to $500',
        description: 'Premier sportsbook with live events and casino integration.',
        tags: ['all', 'sports'],
        rating: 4.5,
        reviewCount: 890,
        withdrawalTime: '~10 mins',
        certified: true,
    },
    {
        id: 'gamdom',
        name: 'Gamdom',
        logo: 'https://files.catbox.moe/jav4a4.jpg',
        bonus: '150% up to 1 BTC',
        description: 'Fun, rewarding platform with rain bonuses and community challenges.',
        tags: ['all', 'high-bonus'],
        rating: 4.6,
        reviewCount: 512,
        withdrawalTime: '~8 mins',
        certified: true,
    },
    {
        id: 'rollbit',
        name: 'Rollbit',
        logo: 'https://files.catbox.moe/wpp3nk.jpg',
        bonus: 'Up to $5000 Rakeback',
        description: 'Innovative NFT marketplace meets high-stakes crypto casino action.',
        tags: ['all', 'live'],
        rating: 4.9,
        reviewCount: 1542,
        withdrawalTime: '~2 mins',
        certified: true,
    },
    {
        id: 'shuffle',
        name: 'Shuffle',
        logo: 'https://files.catbox.moe/pkbfod.png',
        bonus: '100% up to €100',
        description: 'Shuffle up with seamless crypto deposits and diverse table games.',
        tags: ['all', 'live'],
        rating: 4.3,
        reviewCount: 205,
        withdrawalTime: '~15 mins',
        certified: false,
    },
    {
        id: 'rainbet',
        name: 'Rainbet',
        logo: 'https://files.catbox.moe/0jft4x.jpg',
        bonus: '200% up to 2.5 BTC',
        description: 'Generous rain features and a storm of crypto promotions.',
        tags: ['all', 'high-bonus'],
        rating: 4.4,
        reviewCount: 332,
        withdrawalTime: '~20 mins',
        certified: false,
    },
    {
        id: 'roobet',
        name: 'Roobet',
        logo: 'https://files.catbox.moe/of4dut.jpg',
        bonus: 'Up to $80 Bonus',
        description: 'Roobet delivers crash games and live dealers with crypto flair.',
        tags: ['all', 'sports', 'live'],
        rating: 4.2,
        reviewCount: 987,
        withdrawalTime: '~12 mins',
        certified: true,
    },
    {
        id: 'bc-game',
        name: 'BC.GAME',
        logo: 'https://files.catbox.moe/810c57.jpg',
        bonus: '360% up to $20,000',
        description: 'Multi-chain support and thousands of games for every crypto enthusiast.',
        tags: ['all', 'high-bonus', 'live'],
        rating: 4.7,
        reviewCount: 1845,
        withdrawalTime: '~6 mins',
        certified: true,
    },
    {
        id: 'yeet',
        name: 'Yeet',
        logo: 'https://files.catbox.moe/6kol09.jpg',
        bonus: '100% up to 1 BTC',
        description: 'Yeet your bets with speed and style in this rising crypto star.',
        tags: ['all', 'new'],
        rating: 4.1,
        reviewCount: 98,
        withdrawalTime: '~18 mins',
        certified: false,
    },
    {
        id: '500-casino',
        name: '500 Casino',
        logo: 'https://files.catbox.moe/da6qov.jpg',
        bonus: '100% up to $500',
        description: '500 ways to win with crypto slots and progressive jackpots.',
        tags: ['all'],
        rating: 4.0,
        reviewCount: 450,
        withdrawalTime: '~25 mins',
        certified: true,
    },
    {
        id: 'betfury',
        name: 'BetFury',
        logo: 'https://files.catbox.moe/tw3eoe.jpg',
        bonus: '125% up to 1.25 BTC',
        description: 'Fury of bets with staking rewards and live casino thrills.',
        tags: ['all', 'high-bonus'],
        rating: 4.5,
        reviewCount: 680,
        withdrawalTime: '~10 mins',
        certified: true,
    },
    {
        id: 'blockbet',
        name: 'BlockBet',
        logo: 'https://files.catbox.moe/e6i3yr.jpg',
        bonus: '100% up to 1 BTC',
        description: 'Blockchain-powered betting for sports and casino perfection.',
        tags: ['all', 'sports', 'new'],
        rating: 4.3,
        reviewCount: 150,
        withdrawalTime: '~14 mins',
        certified: false,
    },
    {
        id: 'razed',
        name: 'Razed',
        logo: 'https://files.catbox.moe/xvg0gy.jpg',
        bonus: '150% up to €300',
        description: 'Raze the competition with high-RTP crypto games.',
        tags: ['all', 'new'],
        rating: 4.2,
        reviewCount: 75,
        withdrawalTime: '~22 mins',
        certified: false,
    },
    {
        id: 'chips',
        name: 'Chips',
        logo: 'https://files.catbox.moe/x0zu6m.jpg',
        bonus: '100% up to $100',
        description: 'Stack your chips in poker and beyond with crypto ease.',
        tags: ['all', 'live'],
        rating: 4.6,
        reviewCount: 310,
        withdrawalTime: '~9 mins',
        certified: true,
    },
    {
        id: 'duelbits',
        name: 'Duelbits',
        logo: 'https://files.catbox.moe/e8i1og.jpg',
        bonus: 'Up to $100 Bonus',
        description: 'Duel it out in bits with provably fair crypto duels.',
        tags: ['all', 'sports', 'live'],
        rating: 4.7,
        reviewCount: 880,
        withdrawalTime: '~5 mins',
        certified: true,
    },
    {
        id: 'metawin',
        name: 'MetaWin',
        logo: 'https://files.catbox.moe/yr8ksr.jpg',
        bonus: 'No Deposit Needed',
        description: 'Metaverse meets wins in this innovative crypto hub.',
        tags: ['all', 'new'],
        rating: 3.9,
        reviewCount: 45,
        withdrawalTime: '~30 mins',
        certified: false,
    },
    {
        id: 'whale-io',
        name: 'Whale.io',
        logo: 'https://files.catbox.moe/7zy00k.jpg',
        bonus: '200% up to 5 BTC',
        description: 'Dive deep with whale-sized bonuses and crypto pools.',
        tags: ['all', 'high-bonus', 'new'],
        rating: 4.8,
        reviewCount: 250,
        withdrawalTime: '~10 mins',
        certified: true,
    },
    {
        id: 'goated',
        name: 'Goated',
        logo: 'https://files.catbox.moe/qp4oyy.jpg',
        bonus: '100% up to €200',
        description: 'GOATed selections for elite crypto gamblers.',
        tags: ['all', 'new', 'live'],
        rating: 4.4,
        reviewCount: 110,
        withdrawalTime: '~15 mins',
        certified: false,
    },
    {
        id: 'moonroll',
        name: 'Moonroll',
        logo: 'https://files.catbox.moe/n7pja5.jpg',
        bonus: '150% up to 1.5 BTC',
        description: 'Roll to the moon with cosmic crypto adventures.',
        tags: ['all'],
        rating: 4.1,
        reviewCount: 195,
        withdrawalTime: '~12 mins',
        certified: true,
    }
];