
export const mockCasinosData = [
    {
        id: 'duel',
        name: 'Duel',
        logo: 'https://files.catbox.moe/p4z3v7.jpg',
        bonus: '$12M MONTHLY LEADERBOARDS',
        description: 'Pure-variance singularity. 100% RTP originals, true anon (username only), infinite withdrawals. The tactical manifesto against rigged empires.',
        tags: ['all', 'zero-edge', 'crypto-only', 'anon', 'new'],
        rating: 5.0,
        reviewCount: 420,
        withdrawalTime: 'INSTANT (∞ LIMITS)',
        certified: true,
        status: 'VERIFIED',
        specialRanking: 'ETERNAL CROWN',
        license: 'Anjouan (ALSI-202411026-FI1) — Full wagering authorization',
        paymentMethods: 'Crypto-exclusive (BTC, ETH, LTC, USDT); Fee-less, Unbounded',
        founder: 'Ossi "Monarch" Ketola (Ex-CSGOEmpire CEO)',
        company: 'Immortal Snail LLC (Nevis)',
        established: '2025',
        languages: 'English core; Crypto-universal',
        kycPolicy: {
            level1: 'NONE — Username + Password only. No email required.',
            level2: 'N/A — Pure Anon Deployment.',
            level3: 'N/A — AML shadows bypassed by design.',
            level4: 'N/A — VPN-optimized for global shadows.'
        },
        restrictedTerritories: 'USA, UK, Australia, France, Netherlands (Standard Anjouan)',
        companySize: '~25 staff; $12M+ monthly leaderboard expenditure (Founder-backed liquidity)',
        zeroEdgeIntel: {
            rtp: '100% (Originals)',
            houseEdge: '0%',
            kycFriction: 'ZERO (0)',
            withdrawalLimits: '∞ (INFINITE)',
            leaderboardMonthly: '$12,000,000+ USD',
            mathThesis: 'No tailwind + no caps = whale-scale explosions. Bankruptcy-risk model sustained by founder liquidity.'
        }
    },
    {
        id: 'stake',
        name: 'Stake',
        logo: 'https://files.catbox.moe/klt24q.jpg',
        bonus: '200% Welcome Surge',
        description: 'Crypto colossus with 11K+ games and VIP sportsbooks. The strategic nexus for global wager flows, balancing elite liquidity with KYC drag.',
        tags: ['all', 'high-bonus', 'sports', 'live', 'vip'],
        rating: 4.9,
        reviewCount: 2133,
        withdrawalTime: '~5 mins',
        certified: true,
        status: 'VERIFIED',
        license: 'Curaçao eGaming; Colombia, Mexico, Peru licensed',
        paymentMethods: '20+ Cryptos (BTC, ETH, USDT, DOGE, EOS...); Fiat On-Ramps',
        founder: 'Edward Craven & Bijan Tehrani',
        company: 'Medium Rare N.V.',
        established: '2017',
        languages: '15+ (English, Spanish, Portuguese, Japanese, etc.)',
        kycPolicy: {
            level1: 'Email/DOB on registration',
            level2: 'ID scan pre-withdrawal standard',
            level3: 'Address + Payment proof for >$10K',
            level4: 'Enhanced Due Diligence for VIPs; Mandatory for fiat exits'
        },
        restrictedTerritories: 'USA, UK, Australia, Netherlands, Czech Republic',
        companySize: '200+ staff; $1B+ annual (Crypto volume leader)'
    },
    {
        id: 'whale-io',
        name: 'Whale.io',
        logo: 'https://files.catbox.moe/7zy00k.jpg',
        bonus: '200% BTC Bonus',
        description: 'Streamlined crypto predator optimized for VPN-based high-stakes hunts. Rapid scaling entrant with robust infra.',
        tags: ['all', 'high-bonus', 'new', 'vpn-friendly'],
        rating: 4.8,
        reviewCount: 250,
        withdrawalTime: '~10 mins',
        certified: true,
        status: 'VERIFIED',
        license: 'Curaçao Gaming Board (CGB)',
        paymentMethods: '10+ Cryptos; Fiat (Apple/Google Pay, Visa/MC)',
        founder: 'Anonymous (2024 Launch Team)',
        company: 'Whale Entertainment Ltd.',
        established: '2024',
        languages: 'English, Arabic, French',
        kycPolicy: {
            level1: 'Basic signup (Email)',
            level2: 'Optional for small crypto withdrawals',
            level3: 'ID + Address mandatory for >$2K',
            level4: 'Full AML for rewards/redemptions'
        },
        restrictedTerritories: 'Australia, USA, UK, France',
        companySize: '~30 staff; Est. $20M (Sports focus)'
    },
    {
        id: 'bc-game',
        name: 'BC.GAME',
        logo: 'https://files.catbox.moe/810c57.jpg',
        bonus: '360% Deposit Match',
        description: 'Massive crypto ecosystem with Lightning Network speeds and 11K+ slots. Community-driven scale.',
        tags: ['all', 'high-bonus', 'live', 'community'],
        rating: 4.7,
        reviewCount: 1845,
        withdrawalTime: '~6 mins',
        certified: true,
        status: 'VERIFIED',
        license: 'Curaçao eGaming',
        paymentMethods: '100+ Cryptos; Fiat via MoonPay; Lightning Network',
        founder: 'Anonymous (Since 2017)',
        company: 'BC.Game Operations N.V.',
        established: '2017',
        languages: '10+ Multi-regional',
        kycPolicy: {
            level1: 'Basic on deposit',
            level2: 'ID often required for first withdrawal',
            level3: 'Address proof for high limits',
            level4: 'Source of Funds for VIP (Enforced regionally)'
        },
        restrictedTerritories: 'USA, China, Australia, Netherlands',
        companySize: '100+ staff; $200M+ annual revenue'
    },
    {
        id: 'duelbits',
        name: 'Duelbits',
        logo: 'https://files.catbox.moe/e8i1og.jpg',
        bonus: 'Up to $100 Free',
        description: 'Esports vanguard with skin trading and live odds. Tactical for competitive wager chains.',
        tags: ['all', 'sports', 'live', 'esports'],
        rating: 4.7,
        reviewCount: 880,
        withdrawalTime: '~5 mins',
        certified: true,
        status: 'VERIFIED',
        license: 'Curaçao (365/JAZ)',
        paymentMethods: 'BTC, ETH, USDT, LTC, CS:GO Skins; Fiat cards',
        founder: 'Undisclosed (2020 Launch)',
        company: 'Liquid Entertainment NV',
        established: '2020',
        languages: 'English, Spanish, Portuguese',
        kycPolicy: {
            level1: 'Electronic check on signup',
            level2: 'ID for withdrawals (Standard)',
            level3: 'Address proof for higher tiers',
            level4: 'Full AML for disputes'
        },
        restrictedTerritories: 'France, USA, Denmark, Aruba, UK',
        companySize: '50+ staff; $100M+ annual revenue'
    },
    {
        id: 'gamdom',
        name: 'Gamdom',
        logo: 'https://files.catbox.moe/jav4a4.jpg',
        bonus: '150% BTC Surge',
        description: 'Bitcoin bastion with high-reward rain features and multi-currency fluidity.',
        tags: ['all', 'high-bonus', 'community', 'rewards'],
        rating: 4.6,
        reviewCount: 512,
        withdrawalTime: '~8 mins',
        certified: true,
        status: 'VERIFIED',
        license: 'Curaçao GCB',
        paymentMethods: 'BTC, ETH, LTC, USDT; Fiat (Cards, E-wallets, Bank)',
        founder: 'Startup Team (2016)',
        company: 'Gamdom Ltd.',
        established: '2016',
        languages: 'English, Japanese, Norwegian, Russian',
        kycPolicy: {
            level1: 'None mandatory for play',
            level2: '